### ISSUE TITLE
Issue about setup.py

### ISSUE THREAD

**Issue by roywithfiringblade** [nxu-robot/PoseCNN_PyTorch#3]
use `python setup.py install` to create the lib,but I got some Problems:
`houghvoting.obj : error LNK2001: 无法解析的外部符号 "private: void __cdecl cv::String::deallocate(void)" (?deallocate@String@cv@@AEAAXXZ)`

**Comment by roywithfiringblade** [comment]
Thanks I can work it out with only torch. But with OpenCV, it would fail. What should i do before compiling? i already added the "include" folder and "opencv_world347d.lib opencv_world347.lib" to the correct path.

**Comment by hz-ants** [comment]
python setup.py install时，sudo apt-get install libeign3-dev libopencv-dev 将/home/*/anaconda3/lib/python...../torch.h中include <torch/extension.h>可通过
